### ISSUE TITLE
bitmaps.h vtanimations.h

### ISSUE THREAD

**Issue by techno94** [fdivitto/FabGL#1]
Hello,
it's an awesome librarie
i don't find how to generate the bitmaps.h
thanks a lot
![img_2334](https://user-images.githubusercontent.com/2470466/53305643-3656af80-3884-11e9-8d1d-fafb04fd601a.JPG)

**Comment by techno94** [comment]
and how to make the vtanimations.h
thanks a lot

**Comment by fdivitto** [comment]
Hello,
I just added img1sprite tool. Please look at:

https://github.com/fdivitto/FabGL/tree/master/tools/img2bitmap <https://github.com/fdivitto/FabGL/tree/master/tools/img2bitmap>

**Comment by fdivitto** [comment]
The content of vtanimations.h is just an ASCII file (ANSI/VT100 codes) converted to C structure. You can find a lot of these files on the net (sometime with ASC extension).
To convert the to C structure just execute (on Linux or Mac):

xxd --include inputfile.asc
