### ISSUE TITLE
Support for DOS font / BBS ANSI /ASCII ART.

### ISSUE THREAD

**Issue by invictus0x0** [fdivitto/FabGL#106]
Hoping to get the dos font Implemented for network terminal, it was the standard on all US English DOS machines from the XT forward.  
https://en.wikipedia.org/wiki/Code_page_437
As requested, I found a bitmap version of the font here,
https://github.com/CP437/PerfectDOSVGA437/raw/master/PerfectDOSVGA437.ttf

**Comment by fdivitto** [comment]
All fixed width fonts of FabGL already contain code page 437.
