### ISSUE TITLE
[Enhancement?]  Enable USB-serial DEBUG port of PCEmulator as COM1:

### ISSUE THREAD

**Issue by guidol70** [fdivitto/FabGL#114]
May be there in the future a chance to have the USB-serial port available as COM1: in the PC-Emulator? 
- Disable it as DEBUG-output and route the serial transfer to the USB-serial port
- maybe setting a baudrate
Or maybe as COM2: if you use your TTL-serial port as COM1: because you got another pinout than the TTGO VGA32 v1.4

**Comment by fdivitto** [comment]
Serial port handling will be implemented in a next step
