### ISSUE TITLE
SDcard mount issues...

### ISSUE THREAD

**Issue by WacKEDmaN** [fdivitto/FabGL#119]
i cant get SDcards working on esp-vga32 v1.4 board...
but! yours is obviously working!!...
ive tried hardware test and PCemulator ,"Mount Failed" or no SD card inserted...

i can read and write with software spi just fine...
what am i missing?!

**Comment by WacKEDmaN** [comment]
my bad... doesnt like the 2.0.1 alpha... works fine with 1.0.6....

**Comment by fdivitto** [comment]
2.0.1 alpha? ESP32 in Arduino arrives up to 1.0.6, isn't it?

**Comment by guidol70** [comment]
> 2.0.1 alpha? ESP32 in Arduino arrives up to 1.0.6, isn't it?

yes - there seems to be a [developer version 2.0.1 alpha](http://arduino-er.blogspot.com/2021/04/install-arduino-esp32-200-alpha1-on.html)

**Comment by WacKEDmaN** [comment]
yup sorry i forgot i had it installed... seems that new version uses way more memory
