### ISSUE TITLE
[Proposal] Split the library into Core and Demos

### ISSUE THREAD

**Issue by abelykh0** [fdivitto/FabGL#121]
The Core library would include display drivers, keyboard and mouse, and sound. The rest, like anything that require WiFi (ICMP.h), emulators (z80.h, i8080.h, etc), terminal would be split into a separate library.

**Comment by fdivitto** [comment]
I know this would make everything more orderly and coherent, but are there any other reasons to divide the library (binary size, compatibility with other libraries, etc...) ?

**Comment by abelykh0** [comment]
> 
> 
> I know this would make everything more orderly and coherent, but are there any other reasons to divide the library (binary size, compatibility with other libraries, etc...) ?
I was thinking more about issues in GitHub. Currently there are 23 issues and only 5 or 6 are about "Core", the rest is about "demos". In any case, it is your library, you can do whatever you want with it, it is just a proposal.
