### ISSUE TITLE
esp_sntp.h: No such file or directory

### ISSUE THREAD

**Issue by wilson3682** [fdivitto/FabGL#123]
When trying to compile the PCEmulator Sample I'm getting this error message:

PCEmulator:40:22: fatal error: esp_sntp.h: No such file or directory
compilation terminated.
exit status 1
esp_sntp.h: No such file or directory

Arduino IDE ver. 1.813 Intalled
esp32 by Espressif Systems version 1.0.6 Installed.

**Comment by fdivitto** [comment]
Which OS?

**Comment by wilson3682** [comment]
Windows 10

**Comment by wilson3682** [comment]
Thanks a lot Fabrizio. I had to update my Arduino version to 1.8.15, I was using version 1.8.13. Now the sketch is compiling without any problems. Thanks again for your Great Job.
