### ISSUE TITLE
No output with 60Hz 15.7KHz modeline

### ISSUE THREAD

**Issue by Velyks** [fdivitto/FabGL#13]
Possibly a little out of scope but I'm trying to use this library to generate 15Khz test signals for standard definition TVs and arcade monitors and I get no sync or colour output when using the following mode line (Capcom CPS2's resolution):

`"384x224@60Hz" 8.040 384 403 440 511 224 236 239 262  -HSync -VSync`

However I do get output with the following:

`"384x224@50Hz" 8.000 384 404 441 512 224 262 265 312  -HSync -VSync`

Trying to debug it hasn't gotten me very far.

Edit:
This is in 8-color mode

**Comment by fdivitto** [comment]
Unfortunately not all frequencies are supported. I suggest you to check output using an oscilloscope (or frequency counter) and the demo named SquareWaveGenerator, and see which is the exact generated frequency.
