### ISSUE TITLE
 MultitaskingCPM: bug...

### ISSUE THREAD

**Issue by Unixware** [fdivitto/FabGL#137]
I did some testings and I ve found that the MultitaskingCPM has the same bug like:
https://github.com/MockbaTheBorg/RunCPM/issues/45

**Comment by fdivitto** [comment]
fixed thanks!

**Comment by Unixware** [comment]
thanks but I can't close this bug
The libraries are outdated and cant program the ESP32 as there are compiler errors (as both the new keyboard layouts you set are non-existent on 1.0.2/1.0.3 FabGL libs)

**Comment by fdivitto** [comment]
What do you use to compile (Arduino, IDF...)?
