### ISSUE TITLE
License Is Unclear

### ISSUE THREAD

**Issue by bettio** [fdivitto/FabGL#138]
This project at a first glance looks like GPLv3 dual-licensed, which is fine.
However some statements are confusing and might lead to an uncertain interpretation or even completely void the GPLv3 license.

First of all "GPL license version 3, for non-commercial use" cannot be stated, according to FSF guidelines.

Sadly we were thinking about using this as an addition to a free software that we are developing as a community effort, but at the moment we are not further investigating it, since it might be risky for this specific licensing issue.

If you want a commercial model I suggest you to leave everywhere just the GPLv3 license which is a already a strong restriction for practical commercial usages (especially when doing firmware).

Last but not least I suggest you to clarify your position here since the existing source code forks have likely all void licenses.

I suggest you to look at this as an example: https://www.qcustomplot.com/ about "commercial license".

**Comment by fdivitto** [comment]
it should now be clear
