### ISSUE TITLE
Example/UI mouse cannot be controlled

### ISSUE THREAD

**Issue by LilyGO** [fdivitto/FabGL#15]
![image](https://user-images.githubusercontent.com/31160602/58680428-3fcb4880-839a-11e9-9839-73bb4bcb539d.png)
I tried Mouse to work independently and the screen was full of images. But I can't control the cursor.
Of course, I have already confirmed in another Mouse_demo that the mouse can be used normally. look forward to your reply.
Finally, this is an elegant and interesting project. Thank you

**Comment by fdivitto** [comment]
Which example are you testing? Please can you download current version and try the UI demo?

I'm sure you have already done this, but I have to tell: have you put the mouse on port 0 (where is the keyboard)?

**Comment by LilyGO** [comment]
I found the place where the problem is.Change port 0 to port 1,The mouse works fine

But I still can't get the keyboard and mouse to work at the same time.
Do you have a program recommendation?

**Comment by fdivitto** [comment]
To have both mouse and keyboard set:
```
#define KEYBOARD_ON_PORT0                0
#define MOUSE_ON_PORT0                   0
#define KEYBOARD_ON_PORT0_MOUSE_ON_PORT1 1
```

connect keyboard on port 0 and mouse on port 1. A demo that uses both is UI (still in developing state) or the Space Invaders.

**Comment by LilyGO** [comment]
The first time I chose this option was in Space Invaders., but my mouse didn't work.

**Comment by fdivitto** [comment]
please can you send me the schema of your board (privately if you prefer)?

**Comment by LilyGO** [comment]
OK, I will send you the schematic.
