### ISSUE TITLE
No concept of "just a keyboard".

### ISSUE THREAD

**Issue by paulscottrobson** [fdivitto/FabGL#17]
Trying to make an emulator work without resorting to rewriting the scan decoding. This involves the typical old fashioned design where there is a matrix of keys, and you see which are pressed and not, and return an appropriate bit pattern.

As far as I can understand it, you can access the keyboard key state by either catching scancodes on the fly and processing them, or (ii) looking at virtual keys.

The problem with this is there is no easy way of asking the question "is the A key pressed" ? Don't care if it shifted, unshifted , controlled or which other keys are pressed or whatever, just whether the actual key is pressed or not. 

This leads to bizarre behaviour where you can test for Ctrl and C for Ctrl+C but not Shift and C for Shift+C ; presumably because one is defined as an extended virtual key and one isn't.

Suggestion for improvement: option to ignore the extended virtual keys that don't relate to actual physical keyboard keys and simply detect whether a physical key is pressed or not. 

It looks like there is a table of what is physically pressed or not maintained presumably by tracking scan press/releases.

**Comment by fdivitto** [comment]
Thanks for the suggestion. However you can still get scancodes from keyboard, disabling virtual key handling. Look at KeyboardStudio demo and switch to scancode mode. Of course you have to maintain an array of pressed/unpressed keys...
