### ISSUE TITLE
Access to what is, effectively, display memory.

### ISSUE THREAD

**Issue by paulscottrobson** [fdivitto/FabGL#18]
It would be useful to have the functionality to simply abandon all the stuff about drawing with primitives on interrupts etc etc etc and simply access the buffers directly.

**Comment by fdivitto** [comment]
Unfortunately there isn't a single screen buffer, but a linked list of scanlines, which include vertical and horizontal sync signals. You can use VGAController.writeScreen to write directly a rectangle of pixels. No other ways, sorry!
