### ISSUE TITLE
FabGL Network Terminal compatibility issue with non-Nagle-algorithm 

### ISSUE THREAD

**Issue by guidol70** [fdivitto/FabGL#189]
I did try to use the Network Terminal to Telnet to my Telnet-Server-enabled RunCPM on the Deneyap Mini (ESP32-S2) or WeMOS D1 R32
but I got some stange distorted output on some lines :(

Firstly I checked - some hours - the source of the Network-Terminal until I had to blame the ESP32-Telnet-Server code.

First I didnt think about to search the problem in the ESP32-Telnet-Server code, because when I did connect to the ESP32-Telnet-Server via PC/puTTY there was no display-errors.

The distorted output - while using the Network Terminal - results by the ESP32-Telnet-Server option
**server.setNoDelay(true)**

This disables the **Nagle algorithm**:
`The purpose of the Nagle algorithm is to reduce the tcp/ip traffic of small data packets sent over the network by combining some small sending messages and then sending all the messages at once. The disadvantage of this method is that it delays the sending of a single message until a sufficiently large TCP-packet is assembled`

The FabGL Network Terminal seem to have a problem of receiving those small packets and - as metioned in the internet - it looks like a TCP-packet loos.
So the distorted display shows additional space-chars and some incomplete escape-sequences.

After **commenting out the setNoDelay(true)** and re-uploading the code to the VGA32 all output is displayed correct like on PC/puTTY - but with a little delay (because the Telnet-Server does try to fill a complete TCP-packet).
This delay I cant see on PC/puTTY.

I combined the Network Terminal sourcecode with my fork of the FABGL ANSI Terminal (GLTerm - born from RunCPM VGA32 and the FabGL ANSI Terminal)) as **GLnetTerm**.

I removed the serial port configuration from the ConfDialog but keep Terminal-Type, Keyboard, Colors (Fonr/Back/Bold), KeyClick, BREAK-reboot, BootInfo and KeyClick-Toggle via F5 :)

Additionally I created a command cpmnet (like telnet) where the initial negotination isnt included, because the RunCPM doenst ask for Terminal-Type and Resolution.
With the normal telnet I did get some strange control-codes (Ctrl-C?) at the commandline of RunCPM.

Here my version of the source ;)
[GLnetTerm_public_06122021.zip](https://github.com/fdivitto/FabGL/files/7662726/GLnetTerm_public_06122021.zip)

**Comment by badre2911** [comment]
On your source (zip file) you must delete // in front of the instruction:
```
//char const * AUTOEXEC = "info\r"
                           "keyb us\r"
                           "scan\r";
```
otherwise there is a compilation error, because it cannot find AUTOEXEC and an error occurs in "key us\r".
