### ISSUE TITLE
Build error: 'else' without a previous 'if' 

### ISSUE THREAD

**Issue by rdkluijv** [fdivitto/FabGL#193]
Using esp-idf v4.4 and the latest FabGL I get this error:

../components/FabGL/displaycontroller.cpp: In member function 'void fabgl::BitmappedDisplayController::execPrimitive(const fabgl::Primitive&, fabgl::Rect&, bool)':
../components/FabGL/displaycontroller.cpp:786:7: error: 'else' without a previous 'if'
       else
       ^~~~
According to me there is nothing wrong here:
      if (insideISR)
        vTaskNotifyGiveFromISR(prim.notifyTask, nullptr);
      else
        xTaskNotifyGive(prim.notifyTask);
      /*if (insideISR) {
        vTaskNotifyGiveFromISR(prim.notifyTask, nullptr);
      } else {
        xTaskNotifyGive(prim.notifyTask);
      }*/

 Build is fine when the commented out version is used.
Just for information.

**Comment by fdivitto** [comment]
fixed
