### ISSUE TITLE
Cannot set +vsync in VGABaseController::convertModelineToTimings

### ISSUE THREAD

**Issue by rlstrand** [fdivitto/FabGL#197]
I found this while working on connecting to an digital RGBI monitor.
The monitor uses positive hsync and vsync.

I started by using this line:

// Thanks to Paul Rickards (http://biosrhythm.com) - requires upscaler
#define NTSC_640x240_60hz "\"NTSC 640x240 (60Hz)\" 12.312 640 662 719 784 240 244 247 262 -hsync -vsync"

called funcrion with "\"NTSC 640x240 (60Hz)\" 12.312 640 662 719 784 240 244 247 262 +hsync +vsync"

In: bool VGABaseController::convertModelineToTimings(char const * modeline, VGATimings * timings)

Note the following analysis assumes that Hsync must be specified before Vsync.  If not the parser needs more logic.

Once the '+' or '-'for HSync is parsed, the for loop will exit on the space after Hsync via "else if (*pc != ' ')"
VSyncPol is never parsed.

     for (; *pc; ++pc) {
       if (*pc == '+' || *pc == '-') {
         if (!HSyncPol)
           timings->HSyncLogic = HSyncPol = *pc;
         else if (!VSyncPol) {
           timings->VSyncLogic = VSyncPol = *pc;
           while (*pc && *pc != ' ')
             ++pc;
           break;
         }
       } else if (*pc != ' ')
         break;
     }

Fix is to remove the else if (*pc != ' ') conditional and it will work.  
Also remove the while loop in the VSyncPol conditional as it does not need to check for space since already have found Vsync just break out of for loop.

as a note:  Hsync and Vsync can be set with as little as "++" "+-" "-+" "--".

     for (; *pc; ++pc) {
       if (*pc == '+' || *pc == '-') {
         if (!HSyncPol)
           timings->HSyncLogic = HSyncPol = *pc;
         else if (!VSyncPol) {
           timings->VSyncLogic = VSyncPol = *pc;
           break;
         }
       }
     }

**Comment by fdivitto** [comment]
your fix works wonderfully, thank you!!
