### ISSUE TITLE
New Modeline for 640x240_60HZ DoubleScan

### ISSUE THREAD

**Issue by dmcnaugh** [fdivitto/FabGL#2]
You have done an amazing job with this library. Thank you.

Here is a extra Modline that people might find useful:
```
/** Modeline for 640x240@60Hz (DoubleScan) resolution */
#define VGA_640x240_60Hz "\"640x240@60Hz\" 25.175 640 656 752 800 240 245 247 262 -HSync -VSync DoubleScan"
```
It allows you to have 80x24 text with an 8x10 font with an output resolution of 640x480 and not run out of memory.

**Comment by fdivitto** [comment]
Thank you, I'm adding it!

**Comment by fdivitto** [comment]
I have added 8x9 font, so to have more standard 80x25 format. Thanks again!
