### ISSUE TITLE
Suggestions?

### ISSUE THREAD

**Issue by rog77** [fdivitto/FabGL#21]
Sorry if you've heard this a million times already, but...

Is there any way you might consider implementing an xserver and ssh client? Also, I appreciate that this is a VGA library, but other ESP hacks have implemented video out over Composite Video, and analogue broadcast - is it possible to add this? These options would allow your project to bring ultra low cost computing to virtually anyone in the world, on variety of available displays - end users could get free BSD accounts on SDF or the like.

Either way, thanks for considering it!

**Comment by fdivitto** [comment]
Composite video (black/white) may be added in future. Other (ssh, xserver,...) is out of topic for this library,

**Comment by stroobandt** [comment]
@fdivitto I agree with @rog77 An `ssh` secure command line is what would open this project to the world.

**Comment by stroobandt** [comment]
@fdivitto Here is the [source code](http://www.xk72.com/midpssh/v1.7.3/midpssh.zip) of [MidpSSH](http://www.xk72.com/midpssh/), a mobile Java2ME SSH client which runs/ran on old S40 Nokia dumbphones. It can still be used to securely login on modern GNU/Linux machines. This might provide some inspiration...
