### ISSUE TITLE
PS/2 hangs boot on GPIO27

### ISSUE THREAD

**Issue by Tonymac32** [fdivitto/FabGL#22]
Building a hat for my ESP32 board, and for some reason, feeding the PS/2 controller GPIO 27 makes it not start (I had to swap off of pin12 due to strapping).  Is this related to the ULP co-processor, or something I missed elsewhere in the code?  I dont have a pin assignment conflict with the VGA, it's been reassigned as well.

**Comment by fdivitto** [comment]
I'm sorry, I don't know how help you. I have no problem with GPIO27 with the boards I have tested.

**Comment by Tonymac32** [comment]
Thanks for getting back to me, I will recheck this then, it also failed for me on a generic dev board at the time.
