### ISSUE TITLE
No BootSound/KeyClick in RunCPM-FabGL with Fix for ESPCore >=2.0.1

### ISSUE THREAD

**Issue by guidol70** [fdivitto/FabGL#221]
reading that you did fix the compile problem with ESPCore >=2.0.1 in this [commit](https://github.com/fdivitto/FabGL/commit/c096d0f717600d597428922ce0bb08f9f73c4634)
I did try to compile my RunCPM-FabGL with ESP32Core v2.0.1/v2.02

On the normal ArduinoIDE install I did run into compile problems with SDFat (maybe because of many installed boards), so I used a portable Installation of the Arduino IDE (which also did run firstly into problems because of a too long install-path - so moving to C:\ESP_202 :)  )

RunCPM-FabGL compiled under v2.0.1/v2.0.2  with FabGL v1.0.6 OK,

```
Bibliothek SPI in Version 2.0.0 im Ordner: C:\ESP32_202\portable\packages\esp32\hardware\esp32\2.0.1\libraries\SPI  wird verwendet
Bibliothek SdFat in Version 2.1.2 im Ordner: C:\ESP32_202\portable\sketchbook\libraries\SdFat  wird verwendet
Bibliothek FabGL in Version 1.0.6 im Ordner: C:\ESP32_202\portable\sketchbook\libraries\FabGL  wird verwendet
Bibliothek Preferences in Version 2.0.0 im Ordner: C:\ESP32_202\portable\packages\esp32\hardware\esp32\2.0.1\libraries\Preferences  wird verwendet
Bibliothek FS in Version 2.0.0 im Ordner: C:\ESP32_202\portable\packages\esp32\hardware\esp32\2.0.1\libraries\FS  wird verwendet
Bibliothek WiFi in Version 2.0.0 im Ordner: C:\ESP32_202\portable\packages\esp32\hardware\esp32\2.0.1\libraries\WiFi  wird verwendet
"C:\\ESP32_202\\portable\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\gcc8_4_0-esp-2021r2/bin/xtensa-esp32-elf-size" -A "C:\\Users\\guido\\AppData\\Local\\Temp\\arduino_build_995435/RunCPM_VGA32_v5_7_DX__SERCTLFIX15122021.ino.elf"
Der Sketch verwendet 595873 Bytes (45%) des Programmspeicherplatzes. Das Maximum sind 1310720 Bytes.
```

 
but my programmed BootSound and KeyClick is missing :(

In the past I had [ESP32-kernel-reboots because of to less memory](https://github.com/fdivitto/FabGL/issues/152#issuecomment-932988813)
but with the actual compile I have enough memory left:
Free DMA Memory: 38176 Bytes
Free Memory: 95352 Bytes

If I compile the same source (also with FabGL v1.0.6) but with ESP32-Core v1.0.6 the sounds do work.

Do you got an idea why?

**Comment by fdivitto** [comment]
I've rewritten the sound generation code. Please could you take a look?
Thank you
