### ISSUE TITLE
License question, commercial use of this library according to the terms of the GNU GPLv3 license

### ISSUE THREAD

**Issue by renzenicolai** [fdivitto/FabGL#225]
I'd like to confirm something as the LICENSE file (https://github.com/fdivitto/FabGL/blob/master/LICENSE) isn't clear about this.

You state the following:

"FabGL is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version."
  
The GNU GPLv3 allows me to use your software for commercial projects, as long as I comply to the the terms of the GNU GPLv3 license. Most importantly I need to provide access to the full source code for the firmware that I distribute as part of my commercial project. I agree to this license and will make the source code of my firmware available publicly under GNU GPLv3 license.

What I'd like to confirm is the reasoning behind the line "GPL license version 3, for non-commercial use" in your LICENSE file. If I can use your software following the terms described in the GNU GPLv3 license then commercial use is explicitly allowed as additional restrictions may not be applied. Please read section 10 paragraph 3 of the GNU GPLv3 license text. I will quote this text down below.
(https://www.gnu.org/licenses/gpl-3.0.html)

```
You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License. For example, you may not impose a license fee, royalty, or other charge for exercise of rights granted under this License, and you may not initiate litigation (including a cross-claim or counterclaim in a lawsuit) alleging that any patent claim is infringed by making, using, selling, offering for sale, or importing the Program or any portion of it.
```

**Comment by fdivitto** [comment]
The LICENSE file was not updated with the source code header. Now should be ok, thanks!
