### ISSUE TITLE
Unavailable video Modeline for "VGA_480x320_60Hz"...

### ISSUE THREAD

**Issue by exdiogene** [fdivitto/FabGL#236]
Is it possible to get de values for a Resolution Modeline of "VGA_480x320_60Hz" in "fabglconf.h"?

Screens with a 480 x 320 display are quite available at low cost for Arduino and ESP32 projects...

Thank you for your support.

**Comment by badre2911** [comment]
how do you connect a 480x320 screen when fabgl uses VGA?
or do you mean having a resolution of 480x320 on a VGA screen?
what development board are you using?

**Comment by exdiogene** [comment]
Yes I am actually using an autoadjust VGA screen and wanted a resolution of 480x320 on it.

This is the maximum I could use with my actual RAM.

I am using a ESP32-WROOVER...

**Comment by exdiogene** [comment]
Unfortunately, my monitor give the "Unsupported" message with the values of that modeline...

I have tried other combinations like 60Hz and 75Hz refresh to no avail :
#define VGA_480x320_60Hz "\"480x320@60Hz\" 23.83 480 512 552 584 320 326 330 337 -HSync -VSync DoubleScan"
#define VGA_480x320_75Hz "\"480x320@75Hz\" 30.42 480 512 568 600 320 326 330 337 -HSync -VSync DoubleScan"

Same results with those two lines :
#define VGA_480x360_60Hz "\"480x360@60Hz\" 27.08 480 512 560 592 360 367 371 379 -HSync -VSync DoubleScan"
#define VGA_512x340_60Hz "\"512x340@60Hz\" 26.94 512 544 592 624 340 347 351 358 -HSync -VSync DoubleScan"

Even if 480x320 HVGA resolution is popular with Apple, BlackBerry and Android, it seem that it is not recognized by my monitor.

Can you try the two other refresh rate and the two new resolutions on your monitor, just to be sure it is not my own monitor that do not recognize them?

Otherwise I would stick to the 512X384 resolution that give a huge black bar over and under the image with a 512X320 display...

Thank you for your help!

**Comment by fdivitto** [comment]
At the moment I have:
   - Philips LCD 15''
   - HP 2035

Here is my results:

"480x320@60Hz" 23.83 480 512 552 584 320 326 330 337 -HSync -VSync DoubleScan
  - boths not centered, and too much large (need adjusting the image manually)

"480x320@75Hz" 30.42 480 512 568 600 320 326 330 337 -HSync -VSync DoubleScan
  - boths OK, just to center

"480x360@60Hz" 27.08 480 512 560 592 360 367 371 379 -HSync -VSync DoubleScan VisibleBegins
  - boths OK, just to center

"512x340@60Hz" 26.94 512 544 592 624 340 347 351 358 -HSync -VSync DoubleScan
  - unsupported resolution

>>> Even if 480x320 HVGA resolution is popular with Apple, BlackBerry and Android, it seem that it is not recognized by my monitor.

What do you mean exactly? How do you connect these devices to your VGA monitor? Could it be that they use a scaled version of the image?

**Comment by exdiogene** [comment]
It seem that my "Chinese" 13" 16X9 monitor is not responding adequately to those frequencies!

It is normally re-scaling smaller resolutions to fill up the screen, what explain the 2 black bars for 512X384...

I am trying to fit a resolution between 480x320 and 512X320 on that screen, but it seem impossible.

The only resolution working is 512X384 displayed at 512X320 and it is eating all my RAM in double-buffering!

Now that I know that you can see the other resolutions on your monitor, I will try to find another working 12V VGA monitor.

This is for an agricultural project for computer driving tractors using an autonomous RTK-GPS with a precision of 1cm...

Thank you very much for your help.
