### ISSUE TITLE
No Sound with ESP32 Core 2.0.1 but work with ESP32 1.0.6 (Bug)

### ISSUE THREAD

**Issue by badre2911** [fdivitto/FabGL#237]
I have tested sketch DirectVGA_ElMuro on board

fabgl board 3.3v 16MB  no sound
VGA32 No sound

But with ESP32 1.0.6

fabgl board 3.3v it work
VGA32 it work

**Comment by fdivitto** [comment]
are you using the version on github or from library manager of Arduino?

**Comment by badre2911** [comment]
from library manager.

in Menu File->preference for jason file is:

`https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json`

**Comment by fdivitto** [comment]
This has been fixed here:

https://github.com/fdivitto/FabGL/commit/e364d4eb7832257cd3cd8f549cd05e611739293d

so current library on github repo is already fixed. Arduino Library Manager will be updated soon.

**Comment by badre2911** [comment]
Thank you.
