### ISSUE TITLE
font generator

### ISSUE THREAD

**Issue by marcopiai** [fdivitto/FabGL#238]
Hi
Is there a guide or sample step by step to generate file font.h ?
i would like to generate header file with a big font (example arial  in 32 or 46 px)
I have tryed some font ttf to bitmap converter, and after convert with dewinfont.py but without success.

Many thanks

Marco Piai

**Comment by fdivitto** [comment]
I've just added a new script to convert TTF (truetype fonts) to FabGL header.

Install prerequisites with: 

     pip3 install Pillow

Then run it. For example:

     python3 ttf2header.py Arial.ttf 42

The generated file (Arial.h) can be included in your sketch. For example:

===========================================================

#include "fabgl.h"

#define FABGL_FONT_INCLUDE_DEFINITION
#include "Arial.h"

fabgl::VGA8Controller DisplayController;

void setup()
{
  DisplayController.begin();
  DisplayController.setResolution(VGA_640x400_70Hz);
}

void loop()
{
  Canvas cv(&DisplayController);
  cv.setBrushColor(RGB888(0, 0, 0));
  cv.setPenColor(RGB888(255, 255, 255));
  cv.selectFont(&fabgl::FONT_Arial);  
  while (1) {  
     cv.clear();
     cv.drawText(random(-100, 300), random(0, 300), "Hello World!");
     delay(2000);
  }
}
