### ISSUE TITLE
Further VGA Board

### ISSUE THREAD

**Issue by roboticboyer** [fdivitto/FabGL#24]

**Comment by fdivitto** [comment]
Have you tested this board with FabGL? Can you confirm it works with FabGL?

**Comment by roboticboyer** [comment]
Sorry, not yet
Please note that the Bitluni board is not equipped with mouse and keyboard ports, only the VGA adapter and resistors

**Comment by mcuadros** [comment]
I made my own BTW. https://easyeda.com/mcuadros/fabgl-lolind32 and printed in JLCPCB for the price of 24,36e  10uds.

Works perfects besides I forgot link a couple of GND pins of the VGA. I also have a 3d printed box. 
![photo_2019-08-13_20-09-31](https://user-images.githubusercontent.com/1573114/62965983-5f550780-be06-11e9-8a23-9692e7e3dd8c.jpg)

**Comment by kishima** [comment]
I'm also making my FabGL board for ESP32-WROVER-B and a binding for mruby.

![NaryaBoard](https://user-images.githubusercontent.com/291438/62982968-c99e9400-be68-11e9-8e35-908202c6e5fe.jpeg)

https://github.com/kishima/mruby-esp32-narya

For building mruby, I made a FabGL component for ESP-IDF. It can be build with Arduino core for ESP32.

https://github.com/kishima/FabGL_component

**Comment by linker3000** [comment]
Has anyone added sound to Space Invaders? I'd like to demo the ESP32 at a local STEM event and that would be an attention-getter, but I'm not smart enough to modify and test the code in the time before the event!

**Comment by linker3000** [comment]
Breadboarders might be interested in this VGA+keyboard breakout board I laid out.

https://easyeda.com/linker3000/vga-ps2-breakout

**Comment by WacKEDmaN** [comment]
nice one @linker3000 ...needs dual PS/2 tho for keyboard and mouse....
im using a dual stacked header from an old motherboard

**Comment by linker3000** [comment]
@WacKEDmaN Yep. My board was laid out for some retro Z80 work hence no mouse port.

**Comment by douggilliland** [comment]
I made one, too.

http://land-boards.com/blwiki/index.php?title=ESP32-VGA

![ESP32-VGA_P923-720PX](https://user-images.githubusercontent.com/1524110/73142461-e4eb0d80-405c-11ea-9812-73a548c0df45.jpg)

**Comment by fdivitto** [comment]
This is my developing board with micro SD card and all pins exposed (also on [tindie](https://www.tindie.com/products/fabgl/fabgl-development-board/)):

![2019-12-18T17-00-26 601Z-DSC01130](https://user-images.githubusercontent.com/9754506/74035059-d6d0b180-49b9-11ea-846b-12bf015f769a.JPG)

![2019-12-18T17-00-26 601Z-DSC01131](https://user-images.githubusercontent.com/9754506/74035188-17c8c600-49ba-11ea-8037-8866c3b43fbb.JPG)

**Comment by kishima** [comment]
I have updated my board. It supports UART with a GROVE connector and SD card as well.

![narya_board](https://user-images.githubusercontent.com/291438/74092380-3f2ca980-4b06-11ea-839d-73adba5f80c0.jpg)

I also made an editor for Ruby with fabgl::Terminal class. Now I can write and run Ruby code on the board.
![EPiU1fZUEAA43Jl](https://user-images.githubusercontent.com/291438/74092384-4c499880-4b06-11ea-975c-b7feb329331a.jpeg)

[My project site](https://kishima.github.io/family_mruby/)
I appreciate this awesome library.

**Comment by AlyssonRowan** [comment]
An excellent library which hits all of the high points and landmarks for a video terminal.

I am basing a micro terminal project on this library, and on the circuit designs. I only need text mode support, my target being a terminal for my ancient PDP-11 and for an 8052 baed system.

[My projects Blog](https://alyssonrowanprojects.blogspot.com/2020/06/vga-text-terminals-almost-off-shelf.html)

**Comment by PQCraft** [comment]
If any of you wants to test your boards might, I am working on a version of BASIC specifically for the ESP32 and FabGL: [https://github.com/PQCraft/ESPBASIC](https://github.com/PQCraft/ESPBASIC). Keep in mind that it is still in beta. It has awkward bugs that sometimes requires me to just rewrite the entire routine. I also need people to tell me what the bugs are.

**Comment by AlyssonRowan** [comment]
Now that is very interesting. I am still working on my terminal, so I won't be in a position to try this at the moment.

I can see this idea ending up as a replacement for my 8052 microcontroller boards.

**Comment by douggilliland** [comment]
I made a [new version of the card with the SD card socket.](land-boards.com/blwiki/index.php?title=ESP32-VGA) 
<img src="http://land-boards.com/blwiki/images/7/72/P968-cropped-720pxV.jpg"></img>

**Comment by fdivitto** [comment]
### [FabGL Development Board with I/O Extender and PSRAM](https://www.tindie.com/products/24612/)
#### Features:
- **WROVER-E** based with **16MB Flash** and **4MB PSRAM**
- **VGA** video output
- **Audio** output (line level)
- **PS/2 Mouse** and **Keyboard** inputs
- **Micro SD** socket
- I/O extender with **16 GPIOs** (3.3V max voltage, MCP23S17 based)
- firmware upload up to 460800 bps (uses CH340C USB-Serial chip)

Supports all FabGL applications, including the PC Emulator: now you can program your I/O pins using GWBasic or QBASIC under MSDOS!!

Compatible with [LEDs and Buttons board](https://www.tindie.com/products/24613/)

[Purchasing this board](https://www.tindie.com/products/24612/) you support the FabGL project!

Examples with pluggable LEDs and Buttons board:
- [Video Example 1](https://www.youtube.com/watch?v=O9AP4vZHfjI)
- [Video Example 2](https://www.youtube.com/watch?v=JrENR8zDtyU)


![](http://www.fabglib.org/images/devboard3v3.JPG)

**Comment by fdivitto** [comment]
from now on please post new boards into "discussions"
