### ISSUE TITLE
font generation

### ISSUE THREAD

**Issue by mcuadros** [fdivitto/FabGL#25]
I wonder if a guide to generate fonts from TFT can be provided.
Something more like the [font generator](https://github.com/adafruit/Adafruit-GFX-Library/tree/master/fontconvert) from GFX 

I tried to convert TFT to FON with https://loboris.eu/ttf2fon/ttf_convert.py, but when I use the font coverter just fails:

```
python3 dewinfont.py -h ariblk20.fon
ariblk20.fon
Face name not contained within font dataTraceback (most recent call last):
  File "dewinfont.py", line 502, in <module>
    savefont_h(fonts[i], fp) if outext == ".h" else savefont(fonts[i], fp)
  File "dewinfont.py", line 78, in savefont_h
    fname = re.sub('[^0-9a-zA-Z]+', '_', f.facename)
AttributeError: 'NoneType' object has no attribute 'facename'
```

**Comment by fdivitto** [comment]
Can you send me the generated ariblk20.fon for tests?
