### ISSUE TITLE
Compilation doesn't seem to work due to i2c bug?

### ISSUE THREAD

**Issue by ireece1** [fdivitto/FabGL#270]
I just installed your library to test some things out, but it won't let me verify and upload my program to my TTGO board

c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp: In function 'int fabgl::i2cGetFrequency(uint8_t)':
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:169:3: error: 'i2cGetClock' was not declared in this scope
   i2cGetClock(i2c_num, &r);
   ^~~~~~~~~~~
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp: In function 'void fabgl::i2cSetFrequency(uint8_t, int)':
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:174:3: error: 'i2cSetClock' was not declared in this scope
   i2cSetClock(i2c_num, freq);
   ^~~~~~~~~~~
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp: In static member function 'static void fabgl::I2C::commTaskFunc(void*)':
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:230:33: error: invalid conversion from 'unsigned char' to 'i2c_t*' {aka 'i2c_struct_t*'} [-fpermissive]
       job->lastError = i2cWrite(i2c, job->address, job->buffer, job->size, job->timeout);
                                 ^~~
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:230:88: error: too few arguments to function 'i2c_err_t i2cWrite(i2c_t*, uint16_t, uint8_t*, uint16_t, bool, uint16_t)'
       job->lastError = i2cWrite(i2c, job->address, job->buffer, job->size, job->timeout);
                                                                                        ^
In file included from C:\Users\Reece Zahacy\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\cores\esp32/esp32-hal.h:79,
                 from c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.h:40,
                 from c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:33:
C:\Users\Reece Zahacy\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\cores\esp32/esp32-hal-i2c.h:46:11: note: declared here
 i2c_err_t i2cWrite(i2c_t * i2c, uint16_t address, uint8_t* buff, uint16_t size, bool sendStop, uint16_t timeOutMillis);
           ^~~~~~~~
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:232:32: error: invalid conversion from 'unsigned char' to 'i2c_t*' {aka 'i2c_struct_t*'} [-fpermissive]
       job->lastError = i2cRead(i2c, job->address, job->buffer, job->size, job->timeout, &job->readCount);
                                ^~~
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:232:89: error: invalid conversion from 'uint32_t*' {aka 'unsigned int*'} to 'uint16_t' {aka 'short unsigned int'} [-fpermissive]
       job->lastError = i2cRead(i2c, job->address, job->buffer, job->size, job->timeout, &job->readCount);
                                                                                         ^~~~~~~~~~~~~~~
c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:232:104: error: too few arguments to function 'i2c_err_t i2cRead(i2c_t*, uint16_t, uint8_t*, uint16_t, bool, uint16_t, uint32_t*)'
       job->lastError = i2cRead(i2c, job->address, job->buffer, job->size, job->timeout, &job->readCount);
                                                                                                        ^
In file included from C:\Users\Reece Zahacy\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\cores\esp32/esp32-hal.h:79,
                 from c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.h:40,
                 from c:\Users\Reece Zahacy\Documents\Arduino\libraries\FabGL\src\comdrivers\tsi2c.cpp:33:
C:\Users\Reece Zahacy\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\cores\esp32/esp32-hal-i2c.h:47:11: note: declared here
 i2c_err_t i2cRead(i2c_t * i2c, uint16_t address, uint8_t* buff, uint16_t size, bool sendStop, uint16_t timeOutMillis, uint32_t *readCount);
           ^~~~~~~
Compilation error: exit status 1}

**Comment by fdivitto** [comment]
please try last commit, it should fix this problem
