### ISSUE TITLE
VIC20 Basic - How to save program

### ISSUE THREAD

**Issue by roboticboyer** [fdivitto/FabGL#29]
I have written a basic program in Commodore Basic. It's work
I tried saving it using `SAVE "gio",8` but without success
How can I do it?
Could be useful to add a virtual disk in SPIFFS to save the BAS programs

**Comment by fdivitto** [comment]
sorry, at the moment saving and loading (from disk or tape) is not available. Programs can be only injected using the UI.

**Comment by rrosin** [comment]
It might be an option to just save the entire VIC20 ram into SPIFFS
