### ISSUE TITLE
Regarding 8 colour mode...

### ISSUE THREAD

**Issue by dmcnaugh** [fdivitto/FabGL#3]
The advantage of 8 colour mode is that it leaves 3 GPIOs available for other purposes.
It doesn't save memory, as the same pixel buffer is allocated as you get with 64 colour mode.

Is there a way the library could be modified to pack 2 x 8 colour (3 bit) pixels into a single byte in the (pixel) dma_buffer? Maybe it is possible to place the pixel from 2 consecutive lines in the same byte?

The aim is to try and conserve dma memory as the Esp32 is limited in this resource, and it would enable some higher resolutions like 800x600 without running out of memory?

**Comment by fdivitto** [comment]
I'm sorry, I was not able to find a way to do it. Unfortunately ESP32 technical documentation about I2S doesn't help a lot :-(
