### ISSUE TITLE
Computing new modelines

### ISSUE THREAD

**Issue by apuder** [fdivitto/FabGL#30]
First of all: this is a wonderful and amazing project! Kudos to its creator! I want to use FabGL for another retro platform (the TRS-80) and I would need a screen resolution of 512x192. I used this online modeline calculator https://arachnoid.com/modelines/ Needless to say that the results didn't work. I am curious how to properly compute modelines. Any guidance would be greatly appreciated. TIA.

**Comment by fdivitto** [comment]
I've just added 512x192 modeline. It required a "QuadScan" option in modeline syntax.
