### ISSUE TITLE
FabGL dev.board I/O Expander from GWBASIC?

### ISSUE THREAD

**Issue by vitasam** [fdivitto/FabGL#301]
Hello,
I was trying [GPIOGW.BAS](https://github.com/fdivitto/FabGL/blob/master/Extras/PC%20Emulator%20BASIC%20Programs/GPIOGW.BAS) on the latest FabGL board (3.3v) I bought recently, but it returns following:
`Extended I/O not available on this board!`

Is this BASIC program not relevant for the board? MCP23S17 is installed.

P.S. QBASIC program seems to trigger GPIOs

**Comment by fdivitto** [comment]
Hello,
there is an error in GWBASIC version of that program (I didn't remember that IF..THEN in GWBASIC must be in the same line!!). Please test the [new](https://github.com/fdivitto/FabGL/blob/master/Extras/PC%20Emulator%20BASIC%20Programs/GPIOGW.BAS) version.

Thanks!

**Comment by vitasam** [comment]
Thanks! Interesting, I did not remember about this in GWBASIC too. 
The new code works well.
