### ISSUE TITLE
Keyboard/Mouse read from Serial or Wifi instead of PS2

### ISSUE THREAD

**Issue by terryspitz** [fdivitto/FabGL#31]
I have connected a VGA monitor, but I don't have a PS2 keyboard (or a port to plug it in to).  

I'd like to use another device as the keyboard/mouse, either:
- my laptop connected to the ESP32 via USB - e.g. via the Serial connection
- my phone, using something like https://play.google.com/store/apps/details?id=plasma.remote
- (best of all) an XBox or generic wireless gamepad/controller for playing VGA games!

Would anything like this be possible?  thanks!

**Comment by fdivitto** [comment]
Of course it is possible....but you have to write your own drivers to handle these inputs.
