### ISSUE TITLE
TTGO schematic?

### ISSUE THREAD

**Issue by douggilliland** [fdivitto/FabGL#35]
I bought two of the TTGO builds of this. Very nice. Works well. Trying to figure out the GPIO pins. Most are on the silkscreen. One switch isn't listed. Is there a schematic out there for the TTGO build?

**Comment by fdivitto** [comment]
Please ask TTGO for the schematics.

**Comment by douggilliland** [comment]
Your project is fantastic. Not sure why more people don't understand it. A $12USD ANSI terminal is the killer design for Retro-Computer fans. Keep up the good work.

**Comment by fdivitto** [comment]
Thank you! Actually my first prototype did cost even less. For about 5$ you can purchase an ESP32 board with USB. Add just few resistors looking at this "generic" [schema](http://www.fabglib.org/gen_schema.html).

**Comment by douggilliland** [comment]
I did see the schematic on your site. (As you know) the TTGO design went with different I/O connections. I do think the TTGO card is a good value for money considering it has audio, VGA and 2xPS/2 connectors. 

The only thing about the TTGO card I don't like is the lack of mounting holes.

**Comment by fdivitto** [comment]
There is no difference in terms of GPIOs used: TTGO uses the same pin assignments of my schema. TTGO uses better level shifters (while I use resistors!!) for PS/2 ports. Their board also has external battery support.

**Comment by douggilliland** [comment]
I am trying to do the ANSI terminal. I want to connect it to the 4 pin header on the TTGO card.

Their 4 pin header connects to IO12 and IO2.

Your schematic use IO2 for TX and IO14 for RX.

**Comment by douggilliland** [comment]
![image](https://user-images.githubusercontent.com/1524110/70344526-edc31e00-1827-11ea-9fad-4156796e6285.png)

**Comment by fdivitto** [comment]
You're right, I've just fixed that schema! The unique place where FabGL uses serial RX/TX is in AnsiTerminal example and it uses GPIO12 as RX and GPIO2 as TX.

Thank you!
