### ISSUE TITLE
Converting own sound files

### ISSUE THREAD

**Issue by JKamue** [fdivitto/FabGL#36]
This probably has already been asked before somewhere but I can't find any documentation or tools.
What did you use to convert the speech sample to "int8_t[]"? 
Did you have any special tool for that?

I really love your project!

Thanks for your time!

**Comment by fdivitto** [comment]
I've just uploaded a python script named wav2header. It helps to convert a wav file to C header file.

**Comment by JKamue** [comment]
Works great! Thank you very much!
