### ISSUE TITLE
Using uiApp etc... without a mouse

### ISSUE THREAD

**Issue by dmcnaugh** [fdivitto/FabGL#39]
I would like to use the **ui** with only a keyboard attached  and without a mouse.
I don't even have a few spare pins on my ESP32 that I could pretend are an unconnected mouse.

So when I initialise the `PS2Controller` I use only:

```
PS2Controller.begin(PS2Preset::KeyboardPort0);
```

But then when I try to start a `uiApp` the ESP32 trace dumps and reboots.

Is this possible?

**Comment by fdivitto** [comment]
fixed. Now "mouse only" or "keyboard only" modes are supported.
To enable keyboard only you should write:

PS2Controller.begin(PS2Preset::KeyboardPort0, KbdMode::GenerateVirtualKeys);

(because UI needs virtual keys)
