### ISSUE TITLE
flickering

### ISSUE THREAD

**Issue by techno94** [fdivitto/FabGL#4]
Hello,
it's an awesome librairie
i arrive to collecte data from webpage to display on the vga

but it's flickering
where did i miss something ?
https://pastebin.com/eEhpNwAa

thanks a lot

**Comment by fdivitto** [comment]
Hello,
just few suggestions:

- you may try to execute "Canvas.clear();" only one time (when you got the page, or in setup())

- you may disable background execution with:
  VGAController.enableBackgroundPrimitiveExecution(false);
and add the primitives:
  Canvas.clear();
  Canvas.drawText(10, 40, "affichage ");
  ...etc..    
finally execute all primitives in one step with:
  Canvas.waitCompletion(false);
