### ISSUE TITLE
C64 Emulator

### ISSUE THREAD

**Issue by knopserl** [fdivitto/FabGL#42]
The VIC (VC20 Emulator) is very nice. A C64 emulator would be perfect. 
Could that be "merged" with this projects/code:
https://github.com/matgoebl/esp8266-ntsc-c64-emulator
https://github.com/OtherCrashOverride/frodo-go/releases/tag/20181022
The first one uses some kind of VGA and the other just a Display.

**Comment by fdivitto** [comment]
I have no more to add other than already described here:

https://github.com/fdivitto/FabGL/issues/38
