### ISSUE TITLE
External display

### ISSUE THREAD

**Issue by hpagseddy** [fdivitto/FabGL#44]
Hello, is it possible to connect any kind of display instead of VGA? I want to make a portable version of it

**Comment by barbiani** [comment]
You could dump the framebuffer data to your preferred display memory.

**Comment by fdivitto** [comment]
At the moment the library supports SSD1306 OLED (i2c), ST7789 and ILI9341 SPI TFT displays, other than of course VGA. Please look at the provided examples.

BTW: this is valid just for the version you find here on github. For the Arduino library manager you have to wait for the new release.

**Comment by hpagseddy** [comment]
What about a Nokia 5110 display? That's all i have at the moment

**Comment by fdivitto** [comment]
Planned for a future release
