### ISSUE TITLE
VGA schematic vs Pin Assignment Table issue

### ISSUE THREAD

**Issue by douggilliland** [fdivitto/FabGL#48]
Your table shows the pins reversed from the schematic resistor values. In the schematic R0 is connected to GP22 and R1 is connected to GP21. If R1 is the more significant bit it should go to the lower value resistor but it's shown going to the 800 ohm resistor in the schematic.

![image](https://user-images.githubusercontent.com/1524110/74672783-f9ae5300-517b-11ea-9b2a-b6e310039300.png)

[Table is here](https://github.com/fdivitto/FabGL/blob/master/fabgl%20GPIOs%20assignment.txt)

VGA
HSync => 23
VSync => 15
R0 => 22
R1 => 21
G0 => 19
G1 => 18
B0 => 5
B1 => 4

**Comment by douggilliland** [comment]
The docs could have it backwards in some places. For instance: http://www.fabglib.org/classfabgl_1_1_v_g_a_controller.html#a11b70942a5879a6241dea608b28a65b8

**Comment by douggilliland** [comment]
It contradicts this page:

https://github.com/fdivitto/FabGL/blob/master/fabgl%20GPIOs%20assignment.txt

VGA
  HSync => 23
  VSync => 15
  R0    => 22
  R1    => 21
  G0    => 19
  G1    => 18
  B0    => 5
  B1    => 4

**Comment by bootrino** [comment]
What do you mean by "full scale VGA"?

**Comment by douggilliland** [comment]
VGA analog signals go from 0V to 1V (full-scale). There is a 75 ohm terminator in the VGA device. 3.3V out and the resistor values make a voltage divider with the load resistor in the VGA device.

**Comment by douggilliland** [comment]
Screen brightness is the difference. I switched to the values above and get a much brighter screen. Still within the VGA specification.

**Comment by douggilliland** [comment]
Reading more. The proper peak voltage should be 0.7V for video. I will increase the resistor values to match but 400 is way too high for brightest video.

http://www.microvga.com/faq/electrical/what-are-vga-voltage-levels

**Comment by douggilliland** [comment]
I wonder if it's my monitor? The above page says some like 1V peak, others 0.7V peak. Mine tolerates the 1V well. Maybe the 400/800 works best for 400/800.

**Comment by douggilliland** [comment]
I think just this page might be the backwards part:

https://github.com/fdivitto/FabGL/blob/master/fabgl%20GPIOs%20assignment.txt

**Comment by fdivitto** [comment]
fixed thanks
