### ISSUE TITLE
SD Card not working with FabGL?

### ISSUE THREAD

**Issue by Kaef** [fdivitto/FabGL#49]
Hi,
thank you very much sharing this impressive library.
I try to use the esp32 sd-card in combination with FabGL, but the sd-card does not work.
Does FabGL uses any resources needed by the sd-card subsystem?
If so, would it be possible to solve this issue?
Best regards,
Kaef

**Comment by fdivitto** [comment]
Hi,
please add details. Which board are you using, which pins are connected to the SD Card?

**Comment by Kaef** [comment]
I'm using a TTGO-T8 board, sdcard pins are:
    CS - IO13
    MOSI - IO15
    SCK - IO 14
    MISO - IO2
sdcard is working if I don't use FabGL. When using FabGL the card can not be mounted.

**Comment by fdivitto** [comment]
IO15 is used for VSync

**Comment by Kaef** [comment]
Sorry, missing info.
I use:
    #include <fabgl.h>
    fabgl::VGAController VGAController;
    fabgl::PS2Controller PS2Controller;
    fabgl::Terminal      Terminal;

and in setup() I call:
    VGAController.begin(GPIO_NUM_25, GPIO_NUM_26, GPIO_NUM_27, GPIO_NUM_5, GPIO_NUM_23);

**Comment by fdivitto** [comment]
is this the board are you using?
https://www.aliexpress.com/item/32911178069.html

If so, I should have one to test.

**Comment by Kaef** [comment]
yes, nearly; on my board  "T8 V 1.7.1, 20190702" is printed

**Comment by Kaef** [comment]
Do you have tested another esp32 board using FabGL and sdcard?

**Comment by fdivitto** [comment]
Just the prototypes of my board:
https://www.tindie.com/products/fabgl/fabgl-development-board/

**Comment by Kaef** [comment]
Which pins do you use for sdcard?

**Comment by fdivitto** [comment]
The fabgl defaults. They are listed here:

https://github.com/fdivitto/FabGL/blob/master/fabgl%20GPIOs%20assignment.txt

**Comment by Kaef** [comment]
Thank you very much, I try using the pins you have used and will report if it works.

**Comment by Kaef** [comment]
I can confirm that using the fabgl defaults the sdcard is working.
When using my gpio definitions my test program is also working fine. So I think the problem is in my code, sorry.

**Comment by Kaef** [comment]
Problem solved!
Mounting the sdcard failed because free memory was too low, reducing the FabGl resolutions solves the problem.
