### ISSUE TITLE
Understanding how graphics are drawn in the VIC-20 demo

### ISSUE THREAD

**Issue by stevelord** [fdivitto/FabGL#50]
Hi,

I've been looking through the VIC-20 source as I'd like to port some more machines to FabGL, and I'm really struggling to understand how the screen is drawn. I can see that the machine object is hooked into a displayController, but I can't quite bend my head around how the updates are happening. There isn't really any documentation at this level. I was hoping for a framebuffer but I guess there isn't one.

Is there any chance of docs on how to do things at the lower levels like drawing scanlines? It'd make things a heck of a lot easier to understand.

Cheers,
Steve

**Comment by phreda4** [comment]
HI, I do a scanline drawing in my proyect based in the example directvga

in setup()

```
mainTaskHandle = xTaskGetCurrentTaskHandle();
PS2Controller.begin(PS2Preset::KeyboardPort0); //PS2Preset::KeyboardPort0_MousePort1);

..        
DisplayController.begin();
DisplayController.setDrawScanlineCallback(drawScanline);
..
	DisplayController.setResolution(QVGA_320x240_60Hz); // 40x30

```
the function for draw scanline:

```
// pixel order 2301
void IRAM_ATTR drawScanline(void *arg,uint8_t *dest,int scanLine) {
byte c[2],bf,*a=dest;
uint32_t addrc=scanLine>>3;addrc=(addrc<<3)+(addrc<<5); //*40
uint32_t cc,*ac=&screen[addrc];
for (byte x=SCREEN_W;x!=0;x--)	{ // 80 40
  cc=*ac++;
  c[0]=((cc>>16)&0x3f)|DisplayController.m_HVSync;
  c[1]=((cc>>24)&0x3f)|DisplayController.m_HVSync;
  if (cc&0x80000000) {  // graphics x2
    bf=cc>>(((scanLine>>1)&3)<<2);  
    *a++=*a++=c[(bf>>1)&1];
    *a++=*a++=c[(bf>>0)&1];
    *a++=*a++=c[(bf>>3)&1];
    *a++=*a++=c[(bf>>2)&1];
    continue; }
  bf=romfont[((cc&0xff)<<3)+(scanLine&7)];    
  if (cc&0x40000000) { bf=~bf; }      // neg
  if (cc&0x800000) { bf=blink^bf; } // blink
  if (cc&0x400000) { if ((scanLine&7)==7) { bf=~bf; } } // underline?
  *a++=c[(bf>>5)&1];  
  *a++=c[(bf>>4)&1];  
  *a++=c[(bf>>7)&1];  
  *a++=c[(bf>>6)&1];
  *a++=c[(bf>>1)&1];      
  *a++=c[bf&1];  
  *a++=c[(bf>>3)&1];  
  *a++=c[(bf>>2)&1];
  }
if (scanLine==DisplayController.getScreenHeight()-1) { // signal end of screen
  vTaskNotifyGiveFromISR(mainTaskHandle, NULL); 
  if (millis()&0x100) { blink=0xff; } else { blink=0; } 
  }
}
```

you need fill the scanline with rhe correct pixel order and put the correct sync bits.. I modify a bit the code for access to HVSync bits

the full code is in
https://github.com/phreda4/esp32-forth-computer/blob/main/esp32forthcomputer/esp32forthcomputer.ino
