### ISSUE TITLE
SPIFFS ?

### ISSUE THREAD

**Issue by paulscottrobson** [fdivitto/FabGL#53]
Hi. I am using SPIFFS in a fabgl project and it was terrible, randomly crashing. By chance I came across your Altair code which uses SPIFFS and I noticed all your calls were surrounded by interrupt disabling code. Copying this seems to make it work perfectly.

I was wondering if this is the problem - interrupts in SPIFFS break writing - if it is worth highlighting this in the documentation.

Many thanks

**Comment by fdivitto** [comment]
Hi, last update fixes SPIFFS and interrupts problem, so suspending interrupts is no more required (it has been removed from all examples and internal code).
Of course this needs to be well tested, so your feedbacks are welcome!
Thanks

**Comment by fdivitto** [comment]
please reopen this issue if you find problems. Thanks!
