### ISSUE TITLE
Include 16 Color / 4 Bit Color Mode

### ISSUE THREAD

**Issue by Seifenhase** [fdivitto/FabGL#57]
Hi, 
is it possible to enable a 4 bit color mode?
1 Bit for each color (R/G/B) and 1 Bit for intensity. So you get 16 colors, 8 low intensity and 8 high intensity colors.
This could double the framebuffer memory eg. for terminal use or enable a high resolution 16 color mode.
640 x 480 x 4 Bit = 157 Kb FB Memory
800 x 600 x 4 Bit = 240 Kb FB Memory

**Comment by fdivitto** [comment]
Hi, using I2S device with DMA we cannot send less than 8 bits (consider also we have to send horizontal and vertical sync signals, which consume 2 bits for each byte of the frame buffer).
A different approach has ben done using VGA16Controller, which indeed supports 16 colors with 4 bits for each pixel. Unfortunately it consumes about 30% of one core time: anyway it works and consumes half of the frame buffer size.
