### ISSUE TITLE
micropython library

### ISSUE THREAD

**Issue by calin2k** [fdivitto/FabGL#58]
Hi,
Is there a port of this library for micropython?

**Comment by niutech** [comment]
I have a similar question. I would like to edit and run Micropython scripts on FabGL Dev Board using VGA output and PS/2 keyboard, similar to BASIC interpreter. There is [Micropython firmware for ESP32](https://micropython.org/download/esp32/), but how to link it with FabGL?

**Comment by fdivitto** [comment]
This is interesting, but I don't have the time to do it. Are there clear instructions how to compile micropython for esp32?

**Comment by niutech** [comment]
There is a [Github repo with instructions](https://github.com/micropython/micropython/tree/master/ports/esp32#readme). One option would be to [make FabGL a Micropython module](https://docs.micropython.org/en/latest/develop/extendingmicropython.html). Another one would be to [build Micropython for FreeDOS](https://github.com/micropython/micropython/wiki/Building-micropython-for-FreeDOS) (there is even [prebuilt upython.exe](https://github.com/pohmelie/micropython-freedos/releases)) and use it in PCEmulator.

**Comment by kamo0829** [comment]
I've tried integrating Micropython and FabGL. If you are interested, you may visit my web site http://www.hi-ho.ne.jp/jr2xzy/cat/13-1.html. It is Japanese web site however you can see it by using google translation.
