### ISSUE TITLE
Clock and data pins hard coded as 33 and 32 in ps2controller.cpp

### ISSUE THREAD

**Issue by dmcnaugh** [fdivitto/FabGL#6]
https://github.com/fdivitto/FabGL/blob/ddec1f98b2516ed164a9a884d89e68ebfa353066/src/ps2controller.cpp#L509

After passing down user definable  GPIO pins for the ps2 keyboard clock and data lines all the way from Keyboard.begin() to here, this code then ignores these parameters and hardcodes GPIO pins 33 and 32. 

This should be updated to pass through clkGPIO and datGPIO

**Comment by fdivitto** [comment]
Thanks, just fixed!
