### ISSUE TITLE
Adding additional CP/M drives to Altair 8800

### ISSUE THREAD

**Issue by douggilliland** [fdivitto/FabGL#67]
I'm trying to figure out how to add drives beyond D: to the Altair 8800 with 2.2 CP/M. Tried what seemed obvious (added to the Altair8800 sketch). Not sure what else needs to be done to get beyond the D: drive.

#define DRIVE_D "diskD.dsk"   // D: read/write
**#define DRIVE_E "diskE.dsk"   // E: read/write**
**#define DRIVE_F "diskF.dsk"   // F: read/write**

_and_

 diskDrive.attachFile(3, (String(basepath) + String("/") + String(DRIVE_D)).c_str());

  **Terminal.write("Creating Disk E...        \r");**
  **Terminal.flush();**
  **diskDrive.attachFile(4, (String(basepath) + String("/") + String(DRIVE_E)).c_str());**

  **Terminal.write("Creating Disk F...        \r");**
  **Terminal.flush();**
  **diskDrive.attachFile(5, (String(basepath) + String("/") + String(DRIVE_F)).c_str());**

  // setup SIOs (Serial I/O)

**Comment by fdivitto** [comment]
look for "DISKCOUNT" in "machine.h". Change it from "4" to "6".
Anyway I was not able to format disk "E", but just "D": a bug of Altair FORMAT.COM command?
