### ISSUE TITLE
eInk displays support?

### ISSUE THREAD

**Issue by vitasam** [fdivitto/FabGL#70]
Hello,
have you ever considered about adding eInk display support?
There are quite affordable [displays](https://www.waveshare.com/product/displays/e-paper/epaper-2/4.2inch-e-paper.htm) and [esp32 driver board](https://www.waveshare.com/product/displays/e-paper/driver-boards/e-paper-esp32-driver-board.htm) available.

**Comment by fdivitto** [comment]
I'm sorry, at the moment it is not in my plans
