### ISSUE TITLE
How the text mode works?

### ISSUE THREAD

**Issue by bootrino** [fdivitto/FabGL#72]
I'm curious to understand exactly how the text mode works?  Can you direct me to where the algorithm is in the code?

I'm guessing it does something like have a text mode buffer that is width x height i.e. 80 x 24 = 1920 bytes, and to render a frame you convert each row is text into a graphics buffer which has width of the screen width like 640 pixles and depth of the font height like 10 pixels and you then render than buffer to the display, and repeat until each text row has been displayed - is that how it works?

I've dug through the code but can't find the core of how it works - would you mind please pointing me to the line number where the algorithm starts?

You say it is very CPU intensive taking 30% of a single core. What exactly is it that makes it slow?  What function is imposing the highest cpu?

Also are you planning to do a demo video of all the new features?

thanks!

**Comment by fdivitto** [comment]
Having fixed resolution of 640x480 and a font of 8x14, we have a text buffer of up to 80x34. Each character other than the character index, has foreground and background color and attributes, so it requires 32 bits. So the text buffer requires up to 80x34x4=10625 bytes. You can reduce to 80x24, meaning the text buffer will require 7680 bytes.

How it works? Every 7 visible scanlines (the half of character height) an interrupt is generated. Considering a scanline duration of 31us, we have an interrupt every 7x31=217us, excluding the blank areas (front/back porchs and vertical sync). The interrupt reads the text buffer and fill the next 7 scanlines with the rendered characters, while DMA is displaying previous 7 scanlines.
This way just 14 scanlines needs to be allocated (640x14=8960 bytes).

Handling about 70 interrupts every second and rendering (drawing) characters takes about 30% (about 70000000 CPU cycles) of one CPU core: I'm sorry, I cannot do better!
