### ISSUE TITLE
issue with a "BenQ" mouse

### ISSUE THREAD

**Issue by nippur72** [fdivitto/FabGL#73]
I have a "BenQ" PS/2 mouse that responds normally in `MouseStudio` ("Mouse with a wheel" with delta and buttons -- all seems ok) but the same doesn't work in any of the programs with the graphical UI. The arrow just sits at the center of the screen without moving or clicking.

Another mouse of a different brand does work normally.

**Comment by nippur72** [comment]
forgot to report I'm using a TTGO VGA32 v1.4

**Comment by fdivitto** [comment]
I have just a BenQ but, USB, connected using a USB->PS/2 converter. It works in my tests.
