### ISSUE TITLE
TTGO VGA32 V1.4

### ISSUE THREAD

**Issue by nippur72** [fdivitto/FabGL#74]
(I tried to add this info on the Wiki but it's read only)

TTGO now ships the updated V1.4 version of their board which is FabGL compatible except for 2 of the SD card pins: `MOSI` and `MISO` are `12` and `2` instead of `16` and `17`. 

Regarding this, would be possible to have the GPIO pin assignments in a gloabal header file e.g. `GPIO.h` so it's easier to change them in one single place?

![LILYGO-TTGO-VGA32-V1-4-Controller-PS-2-Mouse-E(1)](https://user-images.githubusercontent.com/2598443/89420002-69b49380-d732-11ea-8fef-99f6d73ea866.jpg)

**Comment by panggihsieh** [comment]
Is it possible to add the x-y-sw joystick to the reserved pinout 2,12,13,14,34,39 in the VIC20 example file?

**Comment by fdivitto** [comment]
Last commit adapts default GPIOs for SD card when TTGO board is detected.

**Comment by WacKEDmaN** [comment]
i just got one of these.... i thought it was quite interesting that the Audio.ino from FabGL is preloaded on it
