### ISSUE TITLE
examples/VGA/AnsiTerminal/configdialog.h  line 189 suffers from cut and paste error. Stopbit prefs not saved

### ISSUE THREAD

**Issue by ve7it** [fdivitto/FabGL#75]
In function saveProps()

`    preferences.putInt("StopBits", parityComboBox->selectedItem() + 1);  `
should be
`    preferences.putInt("StopBits", stopBitsComboBox->selectedItem());`

very cool app! I am using this with a modern S100 fpga based Z80 single board computer as its terminal.
Next update idea for the board would be to include a max3232 ttl to rs232 serial chip!
cheers

**Comment by fdivitto** [comment]
thank you!
