### ISSUE TITLE
Using ps/2 keyboard without resistors

### ISSUE THREAD

**Issue by MarcusLing** [fdivitto/FabGL#78]
Found your lib and i'm interested in only using the ps/2 keyboard part. 

In your ps/2 Schematic you have installed resistors. would it work without them? or they are there to protect the board?

I wont use a ps2 port instead i will hook up ps/2 keyboard into my ESP32 pins

**Comment by WacKEDmaN** [comment]
wont work.. ps/2 needs the data lines pulled up to 5v..
you can do without the port itself... and wire it directly...but you still need the resistors to pull up the data and clock lines... without them you risk a) destroying the esp32 b) the keyboard being destroyed (ive done it myself!)
