### ISSUE TITLE
New Modeline for 800x300@60Hz (DoubleScan) resolution

### ISSUE THREAD

**Issue by dmcnaugh** [fdivitto/FabGL#8]
**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*
No

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*
Add a new modeline as follows
```
/** Modeline for 800x300@60Hz (DoubleScan) resolution */
#define SVGA_800x300_60Hz "\"800x300@60Hz\" 40 800 840 968 1056 300 301 303 314 -HSync -VSync DoubleScan"
```

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*
None

**Additional context**
*Add any other context or screenshots about the feature request here.*
It's working for me, although it might need some tweaking as my monitor sometimes crops 1 pixel at the start or end of every line.

**Comment by fdivitto** [comment]
Added, thanks!
