### ISSUE TITLE
ESP32 USB serial port not supported as serial device under Altair8800

### ISSUE THREAD

**Issue by riwide** [fdivitto/FabGL#83]
I have not been able to get the ESP32 USB serial port connection to host PC active under Altair8800 (CP/M) example, and I assume same problem under CP/M3.
Please can you ensure that use of STAT and DEVICE to select Serial ports under CP/M is clearly documented.
Which setting for serial through USB and which for serial through RX/TX PCB header?

**Comment by fdivitto** [comment]
USB Serial port has been assigned to SIO2. In PCGET and PCPUT SIO2 is seen as "B" (please look at Altair8800 documentation for more details).
