### ISSUE TITLE
VGADirectController 

### ISSUE THREAD

**Issue by fg1998** [fdivitto/FabGL#88]
I´m compiling a project that requires VGADirectController Class. The author says its need the latest (unreleased) version of FabGL.If its true, where I can find it ?
(tryed out with 0.9.0 and its not work) - https://github.com/abelykh0/esp32-z80emu

**Comment by fdivitto** [comment]
just released version 1.0.0, which includes VGADirectController. Anyway VGADirectController interface has changed since its introduction, so the author should adapt his code.
