### ISSUE TITLE
CP/M 3 extension compatibility

### ISSUE THREAD

**Issue by snhirsch** [fdivitto/FabGL#89]
I'm trying to get 'Z3PLUS' to work under MultitaskingCPM and not having much success.  The program was initially unhappy with the odd warm-boot BIOS entry at FD04, so I built a system with BDOS 100h lower and BIOS origin at FD00.  Z3 stopped complaining, but unfortunately does nothing but return to the command prompt.  Do you have any thoughts about what's causing the issue?  The program suite and its documentation are available here:

http://oldcomputers.dyndns.org/public/pub/program/jay95/sage/

**Comment by fdivitto** [comment]
I guess Altair8800 emulator (which is more "open" than MultitaskingCPM) is better for Z3PLUS. I cannot help more on this topic.
