### ISSUE TITLE
VGA pins reversed in "fabgl GPIOs assignment.txt"

### ISSUE THREAD

**Issue by SuperFabius** [fdivitto/FabGL#93]
Hi, VGA out pins assignment in the "**_fabgl GPIOs assignment.txt_**" file for R0/1, B0/1 and G0/1 is "reversed" from the one shown in the reference design in the  /images" folder: "_**schema_VGA64.png**_" (i.e. R0 = GPIO22 and R1 = GPIO21 in the text file, but in the schematic image R0 = GPIO21 and R1 = GPIO22). 
Which one is valid?
Regards.

**Comment by fdivitto** [comment]
just fixed!

grazie Fabio
