### ISSUE TITLE
keypad "delete" and "." key does not return proper keycode with numlock on in ansiterminal demo

### ISSUE THREAD

**Issue by ve7it** [fdivitto/FabGL#98]
Using ansi legacy emulation
The "delete" and "." key is always returning rubout or 7Fh. I believe with numlock on, it should be returning '.' so the keypad
can be used for numeric data entry. I am not very familiar with the code, but I was able to get the correct operation by adding an extra case statement in src/devdrivers/keyboard.cpp - function VirtualKey Keyboard::scancodeToVK()  about line 587.
This code seems to be looking at m_NUMLOCK and forcing the returned keycodes to be the numeric counterpart.
<pre>
      case VK_KP_DELETE:        // ve7it fix ./del issue
        vk = VK_KP_PERIOD;
        break;
</pre>

Great project... hard to believe one has a complete ansi terminal in a box barely big enough for all the connectors!. I am using the terminal emulator as the main console for an old S100 CPM80 computer. The emulator is running on a TTGO 1.4 board with a 3d printed enclosure (can be found at https://www.thingiverse.com/thing:4565213)
![P1010034](https://user-images.githubusercontent.com/784890/109918218-70c16700-7c6b-11eb-9783-ac885e9befe5.JPG)

**Comment by fdivitto** [comment]
Your fix is correct. I've just pushed a commit, thank you!
